# Repository configuration for maccel-rpm-builder
# This file can be used with the Probot Settings app for automated repository configuration

repository:
  name: maccel-rpm-builder
  description: "Automated RPM package builder for maccel mouse acceleration driver"
  homepage: "https://github.com/Gnarus-G/maccel"
  topics: 
    - rpm
    - packaging
    - maccel
    - mouse-acceleration
    - fedora
    - blue-build
    - automation
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Labels for issue and PR management
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: rpm-packaging
    color: 7057ff
    description: Related to RPM package creation
  - name: github-actions
    color: 2088ff
    description: Related to GitHub Actions workflows
  - name: integration
    color: 0e8a16
    description: Integration with other projects